config/routes.rb
Rails.application.routes.draw do
  # root
  root 'public#index'

  # admin
  get  '/admin', to: 'admin#index'
  get  '/admin/logout', to: 'admin#logout'

  get 'api/libs'
  get 'api/depts'
  get 'api/deptsbylib'
  get 'api/hours'

  # get 'api/:month/gethours' => 'api#gethours'
  # get 'api/:day/gethours' => 'api#gethours'
  # get 'api/:week/gethours' => 'api#gethours'
  # get 'api/:lib/gethours' => 'api#gethours'
  # get 'api/:dept/gethours' => 'api#gethours'

  get 'rss', to: 'feeds#index', format: 'rss'
  get 'feed.rss', to: 'feeds#rss', format: 'rss'
  get 'feed', to: 'feeds#rss', format: 'rss'

  # forces the controllers to use the admin name space
  # this is going to allow for the addition of a function to restrict access
  # resources generates all routes for crud of libraries, departments, users, etc.
  scope '/admin' do
    resources :libraries, :departments, :users, :normal_hours, :special_hours, :user_permissions, module: 'admin'
  end

  get '/hours', to: 'public/hours#index'
  get '/admin/departments/list', to: 'departments#index'
end

app/models/normal_hour.rb
# Normal Hour data model use for validating normal hours.
# @author David J. Davis
# @author Tracy McCormick
class NormalHour < ApplicationRecord
  belongs_to :resource, polymorphic: true

  validates :id, numericality: { only_integer: true, allow_nil: true }
  validates :resource_type, inclusion: { in: %w[library department] }

  validates :open_time, presence: true, allow_blank: false
  validates :close_time, presence: true, allow_blank: false

  validates :day_of_week,
            numericality: {
              only_integer: true,
              greater_than: -1,
              less_than_or_equal_to: 6
            }

  validate :day_of_week_set

  # resource_name
  # @author David J. Davis
  # determines if library or department and returns the name of the resource
  def resource_name
    if resource_type == 'department'
      resource = Department.find(resource_id)
      resource.name + ' - ' + resource.library.name
    else
      resource = Library.find(resource_id)
      resource.name
    end
  end

  # hr_start_time
  # @author David J. Davis
  # @return a human readable time string
  def hr_open_time
    human_readable_time(open_time)
  end

  # hr_close_time
  # @author David J. Davis
  # @return a human readable time string
  def hr_close_time
    human_readable_time(close_time)
  end

  # weekday
  # @author David J. Davis
  # @returns the day of the week Monday, Tuesday, Wed etc.
  def weekday
    day = day_of_week.to_i
    Date::DAYNAMES[day]
  end

  # open_close_time
  # @author Tracy A. McCormick
  # @param time a time string from the database
  # @return string containing both the hr_open_time and hr_end_time
  def open_close_time
    open_time.nil? || close_time.nil? ? '' : hr_open_time + ' - ' + hr_close_time
  end

  # comment
  # @author Tracy A. McCormick
  def comment
    open_time.nil? && close_time.nil? ? 'Closed' : ''
  end

  private

  # human_readable_time
  # @author David J. Davis, Tracy A. McCormick
  # @param time a time string from the database
  # @return a human readable time string
  def human_readable_time(time)
    !time.nil? ? time.strftime('%l:%M %p').strip : ''
  end

  # day_of_week_set
  # @author Tracy McCormick
  # @author David J. Davis (Modified)
  # checks to see if the normal hour exists for that day
  # throws an error in the form if exists
  def day_of_week_set
    check = NormalHour.where.not(id: id).where('resource_id = ?', resource_id).where('resource_type = ?', resource_type).where('day_of_week = ?', day_of_week)
    errors.add(:day_of_week, 'already set') if check.exists?
  end
end

app/controllers/admin/normal_hours_controller.rb
# Normal Hours
# @author David J. Davis
# @author Tracy McCormick
# Sets data for views, sets redirects, sets errors

class Admin::NormalHoursController < AdminController

  before_action :set_normal_hour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_rights, only: [:show, :edit, :update, :destroy]
  before_action :check_param_resource_access, only: [:create]

  # GET /admin/normal_hours
  # GET /admin/normal_hours.json
  def index
    @normal_hours = NormalHour.all
  end

  # GET /admin/normal_hours/1
  # GET /admin/normal_hours/1.json
  def show; end

  # GET /admin/normal_hours/new
  def new
    @normal_hour = NormalHour.new
  end

  # GET /admin/normal_hours/1/edit
  def edit; end

  # POST /admin/normal_hours
  # POST /admin/normal_hours.json
  def create
    @normal_hour = NormalHour.new(normal_hour_params)
    respond_to do |format|
      if @normal_hour.save
        notice_str = 'Normal hour was successfully created.'
        format.html { redirect_to @normal_hour, notice: notice_str }
        format.json { render :show, status: :created, location: @normal_hour }
      else
        format.html { render :new }
        format.json { render json: @normal_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/normal_hours/1
  # PATCH/PUT /admin/normal_hours/1.json
  def update
    respond_to do |format|
      if @normal_hour.update(normal_hour_params)
        notice_str = 'Normal hour was successfully updated.'
        format.html { redirect_to @normal_hour, notice: notice_str }
        format.json { render :show, status: :ok, location: @normal_hour }
      else
        format.html { render :edit }
        format.json { render json: @normal_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/normal_hours/1
  # DELETE /admin/normal_hours/1.json
  def destroy
    @normal_hour.destroy
    respond_to do |format|
      notice_str = 'Normal hour was successfully destroyed.'
      format.html { redirect_to normal_hours_url, notice: notice_str }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_normal_hour
    @normal_hour = NormalHour.find(params[:id])
  end

  # check_param_resource_access
  # @author Tracy A. McCormick
  # @date 2/28/2017
  #
  # @description
  # Checks params to see if user has access to the library or department they
  # are trying to set
  def check_param_resource_access
    r_type = params[:normal_hour][:resource_type]
    r_id = params[:normal_hour][:resource_id]
    check_resource_access = (@check_access.granular_permission? r_type, r_id)
    error_str = 'You do not have permission to modify these normal hours.'
    redirect_to normal_hours_url, error: error_str unless check_resource_access
  end

  # authenticate_rights
  # @author David J. Davis
  # @date 10-20-2017
  # @description
  # check_access granular permissions check and error routing
  def authenticate_rights
    check_resource_access = (@check_access.granular_permission? @normal_hour.resource_type, @normal_hour.resource_id)
    error_str = 'You do not have permission create or modify these normal hours.'
    redirect_to normal_hours_url, error: error_str unless check_resource_access
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def normal_hour_params
    params.require(:normal_hour).permit(:resource_type, :resource_id, :day_of_week, :open_time, :close_time)
  end
end

app/helpers/normal_hours_helper.rb
module NormalHoursHelper
end

app/views/admin/normal_hours/_form.html.erb
<div class="normal_hours_form">
<%= form_for(normal_hour) do |f| %>
  <% if normal_hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(normal_hour.errors.count, "error") %> prohibited this normal_hour from being saved:</h2>
      <ul>
      <% normal_hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_type, "Select A Location Type" %>
    <%= f.select :resource_type, ['library', 'department']%>
  </div>

  <div class="department field">
    <%= f.label :resource_id, 'Location' %>
    <%= f.collection_select(:resource_id, Department.all, :id, :reformat_name, {}, { class: 'department' }) %>
  </div>

  <div class="library field">
    <%= f.label :resource_id, 'Location' %>
    <%= f.collection_select(:resource_id, Library.all, :id, :name, {}, { class: 'library' })  %>
  </div>

  <div class="field">
    <%= f.label :day_of_week %>
    <%= f.select :day_of_week, Date::DAYNAMES.zip((0..6).to_a)%>
  </div>

  <div class="field">
    <%= f.label :open_time %>
    <%= f.text_field :open_time, :value => normal_hour.hr_open_time, id: "timepicker", class: 'timepicker' %>
  </div>

  <div class="field">
    <%= f.label :close_time %>
    <%= f.text_field :close_time, :value => normal_hour.hr_close_time, id: 'timepicker', class: 'timepicker' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/admin/normal_hours/edit.html.erb
<h1>Editing Admin Normal Hour</h1>

<%= render 'form', normal_hour: @normal_hour %>

<%= link_to 'Show', @normal_hour %> |
<%= link_to 'Back', normal_hours_path %>

app/views/admin/normal_hours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Normal Hours</h1>

<table>
  <thead>
    <tr>
      <th> Open </th>
      <th> Close </th>
      <th> Weekday </th>
      <th> Department / Library </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @normal_hours.each do |normal_hour| %>
      <tr>
        <td><%= normal_hour.hr_open_time %> </td>
        <td><%= normal_hour.hr_close_time %> </td>
        <td><%= normal_hour.weekday %> </td>
        <td><%= normal_hour.resource_name %> </td>
        <td><%= link_to 'Show', normal_hour %> </td>
        <td><%= link_to 'Edit', edit_normal_hour_path(normal_hour) %> </td>
        <td><%= link_to 'Destroy', normal_hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Normal Hour', new_normal_hour_path %>

app/views/admin/normal_hours/new.html.erb
<h1>New Admin Normal Hour</h1>

<%= render 'form', normal_hour: @normal_hour %>
<%= link_to 'Back', normal_hours_path %>

app/views/admin/normal_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Department / Library:</strong>
  <%= @normal_hour.resource_name %>
</p>

<p>
  <strong> Open: </strong>
  <%= @normal_hour.hr_open_time %>
</p>

<p>
  <strong> Close: </strong>
  <%= @normal_hour.hr_close_time %>
</p>

<p>
  <strong> Weekday: </strong>
  <%= @normal_hour.weekday %>
</p>

<%= link_to 'Edit', edit_normal_hour_path(@normal_hour) %> |
<%= link_to 'Back', normal_hours_path %>