config/routes.rb
Rails.application.routes.draw do
  # root
  root 'public#index'

  # admin
  get  '/admin', to: 'admin#index'
  get  '/admin/logout', to: 'admin#logout'

  get 'api/libs'
  get 'api/depts'
  get 'api/deptsbylib'
  get 'api/hours'

  # get 'api/:month/gethours' => 'api#gethours'
  # get 'api/:day/gethours' => 'api#gethours'
  # get 'api/:week/gethours' => 'api#gethours'
  # get 'api/:lib/gethours' => 'api#gethours'
  # get 'api/:dept/gethours' => 'api#gethours'

  get 'rss', to: 'feeds#index', format: 'rss'
  get 'feed.rss', to: 'feeds#rss', format: 'rss'
  get 'feed', to: 'feeds#rss', format: 'rss'

  # forces the controllers to use the admin name space
  # this is going to allow for the addition of a function to restrict access
  # resources generates all routes for crud of libraries, departments, users, etc.
  scope '/admin' do
    resources :libraries, :departments, :users, :normal_hours, :special_hours, :user_permissions, module: 'admin'
  end

  get '/hours', to: 'public/hours#index'
  get '/admin/departments/list', to: 'departments#index'
end

app/models/department.rb
# Department model for keeping track of libraries sub departments
# @author David J. Davis
# @author Tracy McCormick
class Department < ApplicationRecord
  belongs_to :library, inverse_of: :departments
  has_many :normal_hours, as: :resource
  has_many :special_hours, as: :special

  validates :name, presence: true
  validates :id, numericality: { only_integer: true, allow_nil: true }
  validates :library_id, numericality: {
    only_integer: true,
    allow_nil: false,
    message: '%{value} must not be nil and must be an valid id.'
  }
  validates :description, length: {
    maximum: 500,
    message: '%{value} is too long, \
    please shorten the description to 500 characters.'
  }, allow_blank: true

  # Scope is used in the view to get only departments of with these items
  # example: Departments.sorted
  scope :lib_sorted, (-> { order('library_id ASC') })

  # Formats department name to also show their library.
  # Eliminates confusing like named departments in different libraries.
  # @author David J. Davis
  def reformat_name
    name + ' - ' + library.name
  end
end

app/controllers/admin/departments_controller.rb
# Department Controller
# @author David J. Davis
# @author Tracy McCormick
# @description Sets data for views, sets redirects, sets errors

class Admin::DepartmentsController < AdminController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :allow_admin_only, only: [:create, :new, :destroy]
  before_action :users_can_edit_dept, only: [:show, :edit, :update]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all.joins(:library).order('libraries.name')
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        success_str = 'Department was successfully created.'
        format.html { redirect_to @department, success: success_str }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        success_str = 'Department was successfully updated.'
        format.html { redirect_to @department, success: success_str }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      success_str = 'Department was successfully destroyed.'
      format.html { redirect_to departments_url, success: success_str }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_department
    @department = Department.find(params[:id])
  end

  # allow_admin_only
  # @author: David J. Davis
  # Date : 9/26/2017
  #
  # @description:
  # Users the admin controller to check if the user is an admin.
  # if not a flash message is added to the UI and the user is re-directed.
  def allow_admin_only
    error_string = 'You do not have admin access to edit, create, or delete departments.'
    redirect_to departments_path, error: error_string unless @check_access.admin?
  end

  # users_can_edit_dept
  # @author David J. Davis
  # @date 9/26/2017
  # @description:
  # If the user is not an admin, the next check sees if they have been given
  # permission to edit the details of the department.
  def users_can_edit_dept
    error_str = 'You do not have permission to access this department.'
    redirect_to departments_url, error: error_str unless @check_access.department_permission? params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def department_params
    params.require(:department).permit(:name, :description, :library_id)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :description)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= form_for(department) do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :library_id %>
    <%= f.collection_select(
      :library_id, Library.all, :id, :name,
      { prompt: 'Select A Library' }
    ) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/admin/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Description </th>
      <th> Library </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.description %></td>
        <td><%= department.library.name %> </td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/admin/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/admin/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @department.description %>
</p>

<p>
  <strong> Library: </strong>
  <%= @department.library.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>