config/routes.rb
Rails.application.routes.draw do
  # root
  root 'public#index'

  # admin
  get  '/admin', to: 'admin#index'
  get  '/admin/logout', to: 'admin#logout'

  get 'api/libs'
  get 'api/depts'
  get 'api/deptsbylib'
  get 'api/hours'

  # get 'api/:month/gethours' => 'api#gethours'
  # get 'api/:day/gethours' => 'api#gethours'
  # get 'api/:week/gethours' => 'api#gethours'
  # get 'api/:lib/gethours' => 'api#gethours'
  # get 'api/:dept/gethours' => 'api#gethours'

  get 'rss', to: 'feeds#index', format: 'rss'
  get 'feed.rss', to: 'feeds#rss', format: 'rss'
  get 'feed', to: 'feeds#rss', format: 'rss'

  # forces the controllers to use the admin name space
  # this is going to allow for the addition of a function to restrict access
  # resources generates all routes for crud of libraries, departments, users, etc.
  scope '/admin' do
    resources :libraries, :departments, :users, :normal_hours, :special_hours, :user_permissions, module: 'admin'
  end

  get '/hours', to: 'public/hours#index'
  get '/admin/departments/list', to: 'departments#index'
end

app/models/special_hour.rb
require 'date'
require 'time'
# Special Hour model this is used for adding special hours to the projects
# versus consistent hours from normal hours.
# @author David J. Davis
# @author Tracy McCormick
class SpecialHour < ApplicationRecord
  belongs_to :special, polymorphic: true

  validates :special_id, numericality: { only_integer: true, allow_nil: false }
  validates :special_type, inclusion: { in: %w[library department] }
  validates :id, numericality: { only_integer: true, allow_nil: true }

  # hr_start_date
  # @author David J. Davis
  # @return a human readable date string
  def hr_start_date
    hr_date(start_date)
  end

  # hr_end_date
  # @author David J. Davis
  # @return a human readable date string
  def hr_end_date
    hr_date(end_date)
  end

  # hr_start_time
  # @author David J. Davis
  # @return a human readable time string
  def hr_open_time
    hr_time(open_time)
  end

  # hr_close_time
  # @author David J. Davis
  # @return a human readable time string
  def hr_close_time
    hr_time(close_time)
  end

  # open_close_time
  # @author Tracy A. McCormick
  # @param time a time string from the database
  # @return string containing both the hr_open_time and hr_end_time
  def open_close_time
    !open_time.nil? && !close_time.nil? ? hr_open_time + ' - ' + hr_close_time : ''
  end

  # comment
  # @author Tracy A. McCormick
  # @return a comment string
  def comment
    if open_24 then 'Open 24 Hours'
    elsif no_open_time then 'no open time set'
    elsif no_close_time then 'no close time set'
    else ''
    end
  end

  # get resource
  # @author David J. Davis
  # @return a human readable time string
  def resource_name
    if special_type == 'department'
      special = Department.find(special_id)
      special.name + ' - ' + special.library.name
    else
      special = Library.find(special_id)
      special.name
    end
  end

  private

  # hr_time
  # @param time : a time string from db
  # @author David J. Davis, Tracy A. McCormick
  # @return a human readable time string as 12 hour minute am/pm
  def hr_time(time)
    !time.nil? ? time.strftime('%l:%M %p') : ''
  end

  # hr_time
  # @param date : a datetime string from db
  # @author David J. Davis, Tracy A. McCormick
  # @return a human readable date as full month day, year.
  def hr_date(date)
    !date.nil? ? date.strftime('%B %d, %Y') : ''
  end
end

app/controllers/admin/special_hours_controller.rb
# Special Hours
# @author David J. Davis
# @author Tracy McCormick
# Sets data for views, sets redirects, sets errors

class Admin::SpecialHoursController < AdminController
  before_action :set_special_hour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_rights, only: [:show, :edit, :update, :destroy]
  before_action :check_param_resource_access, only: [:create]

  # validate start_date and end_date
  before_action :check_date_range, only: [:create, :update]
  before_action :check_overlapping_dates, only: [:create]

  # GET /special_hours
  # GET /special_hours.json
  def index
    @special_hours = SpecialHour.all
  end

  # GET /special_hours/1
  # GET /special_hours/1.json
  def show
  end

  # GET /special_hours/new
  def new
    @special_hour = SpecialHour.new
  end

  # GET /special_hours/1/edit
  def edit
  end

  # POST /special_hours
  # POST /special_hours.json
  def create
    @special_hour = SpecialHour.new(special_hour_params)
    respond_to do |format|
      if @special_hour.save
        success_str = 'Special hour was successfully created.'
        format.html { redirect_to @special_hour, success: success_str }
        format.json { render :show, status: :created, location: @special_hour }
      else
        format.html { render :new }
        format.json { render json: @special_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_hours/1
  # PATCH/PUT /special_hours/1.json
  def update
    respond_to do |format|
      if @special_hour.update(special_hour_params)
        success_str = 'Special hour was successfully updated.'
        format.html { redirect_to @special_hour, success: success_str }
        format.json { render :show, status: :ok, location: @special_hour }
      else
        format.html { render :edit }
        format.json { render json: @special_hour.errors, status: :unprocessable_entity }
      end
    end 
  end

  # DELETE /special_hours/1
  # DELETE /special_hours/1.json
  def destroy
    @special_hour.destroy
    respond_to do |format|
      success_str = 'Special hour was successfully destroyed.'
      format.html { redirect_to special_hours_url, success: success_str }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_special_hour
    @special_hour = SpecialHour.find(params[:id])
  end

  # check_time_range
  # @author : David J. Davis
  # @date 10/29/2017
  #
  # @description
  # Throws an error if the end time is before the start time. 
  def check_date_range
    unless dates_present? && valid_date_range?
      error_str = 'Dates are not present or start date is after the end date.'
      redirect_to special_hours_url, error: error_str
    end
  end

  # dates_present 
  # @author : David J. Davis 
  # @date 10/12/2017
  # @description
  # boolean to see if the dates exist in the params 
  def dates_present?
    params[:special_hour][:start_date].present? && params[:special_hour][:end_date].present?
  end

  # valid_date_range?  
  # @author : David J. Davis 
  # @date 10/12/2017
  # @description
  # boolean to see if date ranges are acceptable 
  def valid_date_range?
    start_date = Date.parse params[:special_hour][:start_date]
    end_date = Date.parse params[:special_hour][:end_date]
    start_date <= end_date
  end

  # valid_date_range?
  # @author : David J. Davis
  # @date 10/12/2017
  # @description
  # uses the check_date method to check both posted start and end dates
  def check_overlapping_dates
    start_date = check_date params[:special_hour][:start_date]
    end_date = check_date params[:special_hour][:end_date]
    if start_date || end_date
      error_str = 'Dates can not overlap a library or departments already set dates associated with special open and close times, please check to make sure that there are no other conflicting dates and modify yours accordingly.'
      redirect_to special_hours_url, error: error_str
    else
      true
    end
  end

  # check_date
  # @author : David J. Davis
  # @date 10/30/2017
  # @description
  # returns true if date_to_check is found in any set special_hour
  def check_date date_to_check
    check = Date.parse(date_to_check)
    SpecialHour.where('special_id = ?', params[:special_hour][:special_id]).where('special_type = ?', params[:special_hour][:special_type]).where('start_date <= ?', check).where('end_date >= ?', check).exists?
  end

  # check_param_resource_access
  # @author : Tracy A. McCormick
  # @date 2/28/2017
  #
  # @description
  # Checks params to see if user has access to the library or department they
  # are trying to set
  def check_param_resource_access
    special_type = params[:special_hour][:special_type]
    special_id = params[:special_hour][:special_id]
    check_resource_access = (@check_access.granular_permission? special_type, special_id)
    error_str = "You do not have permission to modify these special hours."
    redirect_to special_hours_url, error: error_str unless check_resource_access
  end

  # authenticate_rights
  # @author : Tracy A. McCormick
  # @date 2/22/2017
  #
  # @description
  # Calls user_has_access to see if they have access to the library or
  # department. Also checks to see if they are admin. If neither of these are
  # true it redirects them back to there previous page and shows them an error.
  def authenticate_rights
    check_resource_access = (@check_access.granular_permission? @special_hour.special_type, @special_hour.special_id)
    @access = check_resource_access
    error_str = 'You do not have permission create or modify these special hours.'
    redirect_to special_hours_url, error: error_str unless check_resource_access
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def special_hour_params
    params.require(:special_hour).permit(:start_date, :end_date, :name, :open_time, :close_time, :open_24, :no_close_time, :no_open_time, :special_type, :special_id)
  end
end

app/helpers/special_hours_helper.rb
module SpecialHoursHelper
end

app/views/admin/special_hours/_form.html.erb
<div class="special-hour-form">
<%= form_for(special_hour) do |f| %>
  <% if special_hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(special_hour.errors.count, "error") %> prohibited this special_hour from being saved:</h2>

      <ul>
      <% special_hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :special_type, "Select A Location Type" %>
    <%= f.select :special_type, ['library', 'department']%>
  </div>

  <div class="field department">
    <%= f.label :special_id, 'Location' %>
    <%= f.collection_select(:special_id, Department.all, :id, :reformat_name, {}, { class: 'department' }) %>
  </div>

  <div class="field library">
    <%= f.label :special_id, 'Location' %>
    <%= f.collection_select(:special_id, Library.all, :id, :name, {}, {:class=>'library'})  %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, value: special_hour.hr_start_date, id: 'datepicker', class: 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.text_field :end_date, :value => special_hour.hr_end_date, id: 'datepicker', class: 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :open_time %>
    <%= f.text_field :open_time, value: special_hour.hr_open_time, id: 'timepicker', class: 'timepicker'  %>
  </div>

  <div class="field">
    <%= f.label :close_time %>
    <%= f.text_field :close_time, value: special_hour.hr_close_time, id: 'timepicker', class: 'timepicker' %>
  </div>


  <div class="field">
    <%= f.label :open_24 %>
    <%= f.check_box :open_24 %>
  </div>

  <div class="field">
    <%= f.label :no_close_time %>
    <%= f.check_box :no_close_time %>
  </div>

  <div class="field">
    <%= f.label :no_open_time %>
    <%= f.check_box :no_open_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/admin/special_hours/edit.html.erb
<h1>Editing Special Hour</h1>

<%= render 'form', special_hour: @special_hour %>

<%= link_to 'Show', @special_hour %> |
<%= link_to 'Back', special_hours_path %>

app/views/admin/special_hours/index.html.erb
<h1>Special Hours</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Open time</th>
      <th>Close time</th>
      <th>Open 24</th>
      <th>No close time</th>
      <th>No open time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_hours.each do |special_hour| %>
      <tr>
        <td><%= special_hour.hr_start_date %></td>
        <td><%= special_hour.hr_end_date %></td>
        <td><%= special_hour.name %></td>
        <td><%= special_hour.hr_open_time %></td>
        <td><%= special_hour.hr_close_time %></td>
        <td><%= special_hour.open_24 ? "yes" : "no" %></td>
        <td><%= special_hour.no_close_time ? "yes" : "no" %></td>
        <td><%= special_hour.no_open_time ? "yes" : "no" %></td>
        <td><%= link_to 'Show', special_hour %></td>
        <td><%= link_to 'Edit', edit_special_hour_path(special_hour) %></td>
        <td><%= link_to 'Destroy', special_hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special Hour', new_special_hour_path %>

app/views/admin/special_hours/new.html.erb
<h1>New Special Hour</h1>

<%= render 'form', special_hour: @special_hour %>

<%= link_to 'Back', special_hours_path %>

app/views/admin/special_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @special_hour.hr_start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @special_hour.hr_end_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @special_hour.name %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @special_hour.hr_open_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @special_hour.hr_close_time %>
</p>

<p>
  <strong>Open 24:</strong>
  <%= @special_hour.open_24 %>
</p>

<p>
  <strong>No close time:</strong>
  <%= @special_hour.no_close_time %>
</p>

<p>
  <strong>No open time:</strong>
  <%= @special_hour.no_open_time %>
</p>

<%= link_to 'Edit', edit_special_hour_path(@special_hour) %> |
<%= link_to 'Back', special_hours_path %>