config/routes.rb
Rails.application.routes.draw do
  # root
  root 'public#index'

  # admin
  get  '/admin', to: 'admin#index'
  get  '/admin/logout', to: 'admin#logout'

  get 'api/libs'
  get 'api/depts'
  get 'api/deptsbylib'
  get 'api/hours'

  # get 'api/:month/gethours' => 'api#gethours'
  # get 'api/:day/gethours' => 'api#gethours'
  # get 'api/:week/gethours' => 'api#gethours'
  # get 'api/:lib/gethours' => 'api#gethours'
  # get 'api/:dept/gethours' => 'api#gethours'

  get 'rss', to: 'feeds#index', format: 'rss'
  get 'feed.rss', to: 'feeds#rss', format: 'rss'
  get 'feed', to: 'feeds#rss', format: 'rss'

  # forces the controllers to use the admin name space
  # this is going to allow for the addition of a function to restrict access
  # resources generates all routes for crud of libraries, departments, users, etc.
  scope '/admin' do
    resources :libraries, :departments, :users, :normal_hours, :special_hours, :user_permissions, module: 'admin'
  end

  get '/hours', to: 'public/hours#index'
  get '/admin/departments/list', to: 'departments#index'
end

app/models/library.rb
# Library data model.
# @author David J. Davis
# @author Tracy McCormick
class Library < ApplicationRecord
  has_many :departments, dependent: :destroy
  has_many :normal_hours, as: :resource
  has_many :special_hours, as: :special

  validates :name, presence: true
  validates :id, numericality: { only_integer: true, allow_nil: true }
  validates :description,
            length: {
              maximum:  500,
              message: '%{value} is too long, shorten to 500 characters.'
            },
            allow_blank: true

  # returns a list of departments, unless the library has no departments.
  # @author David J. Davis
  def opt_groups
    return unless departments.empty?
  end
end

app/controllers/admin/libraries_controller.rb
# Libraries Controller
# @author David J. Davis
# @author Tracy McCormick
# Sets data for views, sets redirects, sets errors

class Admin::LibrariesController < AdminController
  # Before action fires the method assigned to it before
  # other methods are called acting as a filter in some cases
  # or to apply data in a dry aspect in other cases
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :allow_admin_only, only: [:create, :new, :destroy]
  before_action :users_can_edit_library, only: [:show,:edit,:update]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all.order(:name)
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        success_str = 'Library was successfully created.'
        format.html { redirect_to @library, success: success_str }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        success_str = 'Library was successfully updated.'
        format.html { redirect_to @library, success: success_str }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      success_str = 'Library was successfully destroyed.'
      format.html { redirect_to libraries_url, success: success_str }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # allow_admin_only
    # @author David J. Davis
    # @date 2/10/2017
    # @description
    # Users the admin controller to check if the user is an admin.
    # if not a flash message is added to the UI and the user is re-directed.
    def allow_admin_only
      error_string = 'You do not have admin access to edit, create, or delete users.'
      redirect_to libraries_path, error: error_string unless @check_access.admin?
    end

    # users_can_edit_library
    # @author David J. Davis
    # @date 9/26/2017
    # @description
    # checks if is admin or has granular permission 
    def users_can_edit_library
      error_str = 'You do not have permission to access this library.'
      redirect_to libraries_url, error: error_str unless @check_access.library_permission? params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :description)
    end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :hasDepartment, :description)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/admin/libraries/_form.html.erb
<%= form_for(library) do |f| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/admin/libraries/index.html.erb
<h1>Libraries</h1>

<table class="crud-table">
  <thead>
    <tr>
      <th> Name </th>
      <th> Description </th>
      <th> Departments </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.name %></td>
        <td><%= library.description %></td>
        <td>
          <ul>
          <% library.departments.each do |dept| %>
            <li> <%= dept.name %> </li>
          <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to 'New Library', new_library_path %>

app/views/admin/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/admin/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @library.description %>
</p>

<p>
  <strong>Departments: </strong>
  <ul>
    <% @library.departments.each do |dept| %>
      <li> <%= dept.name %> </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>